using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eShopDashboard.Controllers
{
    public class ProductSetDetailsByDescription
    {
        public static string Value => @"
[
  {
    ""id"": 109,
    ""catalogBrandId"": 100,
    ""description"": ""ASSTD DESIGN RACING CAR PEN"",
    ""price"": 3.29,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/109/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": ""asstd"",
    ""agram"": ""racing"",
    ""bgram"": ""car"",
    ""abgram"": ""racing-car"",
    ""ygram"": null,
    ""zgram"": ""pen"",
    ""yzgram"": ""car-pen""
  },
  {
    ""id"": 142,
    ""catalogBrandId"": 100,
    ""description"": ""WRAP CAROUSEL"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/142/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""wrap"",
    ""bgram"": null,
    ""abgram"": null,
    ""ygram"": null,
    ""zgram"": ""carousel"",
    ""yzgram"": ""wrap-carousel""
  },
  {
    ""id"": 153,
    ""catalogBrandId"": 100,
    ""description"": ""WRAP DAISY CARPET"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/153/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": ""daisy"",
    ""quantity"": """",
    ""agram"": ""wrap"",
    ""bgram"": null,
    ""abgram"": null,
    ""ygram"": null,
    ""zgram"": ""carpet"",
    ""yzgram"": ""wrap-carpet""
  },
  {
    ""id"": 163,
    ""catalogBrandId"": 100,
    ""description"": ""CARTOON  PENCIL SHARPENERS"",
    ""price"": 0.06,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/163/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""cartoon"",
    ""bgram"": ""pencil"",
    ""abgram"": ""cartoon-pencil"",
    ""ygram"": null,
    ""zgram"": ""sharpeners"",
    ""yzgram"": ""pencil-sharpeners""
  },
  {
    ""id"": 250,
    ""catalogBrandId"": 100,
    ""description"": ""FLORAL SOFT CAR TOY"",
    ""price"": 3.75,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/250/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": ""floral"",
    ""quantity"": """",
    ""agram"": ""car"",
    ""bgram"": null,
    ""abgram"": null,
    ""ygram"": null,
    ""zgram"": ""toy"",
    ""yzgram"": ""car-toy""
  },
  {
    ""id"": 273,
    ""catalogBrandId"": 100,
    ""description"": ""LUNCH BAG CARS BLUE"",
    ""price"": 1.65,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/273/pic/"",
    ""color"": ""blue"",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""lunch"",
    ""bgram"": ""bag"",
    ""abgram"": ""lunch-bag"",
    ""ygram"": null,
    ""zgram"": ""cars"",
    ""yzgram"": ""bag-cars""
  },
  {
    ""id"": 414,
    ""catalogBrandId"": 100,
    ""description"": ""REX CASH+CARRY JUMBO SHOPPER"",
    ""price"": 0.95,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/414/pic/"",
    ""color"": """",
    ""size"": ""jumbo"",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""rex"",
    ""bgram"": ""cash"",
    ""abgram"": ""rex-cash"",
    ""ygram"": ""carry"",
    ""zgram"": ""shopper"",
    ""yzgram"": ""carry-shopper""
  },
  {
    ""id"": 461,
    ""catalogBrandId"": 100,
    ""description"": ""ROSE CARAVAN DOORSTOP"",
    ""price"": 1.95,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/461/pic/"",
    ""color"": ""rose"",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""caravan"",
    ""bgram"": null,
    ""abgram"": null,
    ""ygram"": null,
    ""zgram"": ""doorstop"",
    ""yzgram"": ""caravan-doorstop""
  },
  {
    ""id"": 474,
    ""catalogBrandId"": 100,
    ""description"": ""VICTORIAN  METAL POSTCARD SPRING"",
    ""price"": 1.69,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/474/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": ""victorian"",
    ""quantity"": """",
    ""agram"": ""postcard"",
    ""bgram"": null,
    ""abgram"": null,
    ""ygram"": null,
    ""zgram"": ""spring"",
    ""yzgram"": ""postcard-spring""
  },
  {
    ""id"": 704,
    ""catalogBrandId"": 100,
    ""description"": ""RED WHITE SCARF  HOT WATER BOTTLE"",
    ""price"": 3.95,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/704/pic/"",
    ""color"": ""red-white"",
    ""size"": """",
    ""shape"": """",
    ""quantity"": ""bottle"",
    ""agram"": ""scarf"",
    ""bgram"": ""hot"",
    ""abgram"": ""scarf-hot"",
    ""ygram"": null,
    ""zgram"": ""water"",
    ""yzgram"": ""hot-water""
  },
  {
    ""id"": 712,
    ""catalogBrandId"": 100,
    ""description"": ""SKULLS GREETING CARD"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/712/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": ""skulls"",
    ""quantity"": """",
    ""agram"": ""greeting"",
    ""bgram"": null,
    ""abgram"": null,
    ""ygram"": null,
    ""zgram"": ""card"",
    ""yzgram"": ""greeting-card""
  },
  {
    ""id"": 713,
    ""catalogBrandId"": 100,
    ""description"": ""FANCY FONT BIRTHDAY CARD-"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/713/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": ""fancy"",
    ""quantity"": """",
    ""agram"": ""font"",
    ""bgram"": ""birthday"",
    ""abgram"": ""font-birthday"",
    ""ygram"": null,
    ""zgram"": ""card"",
    ""yzgram"": ""birthday-card""
  },
  {
    ""id"": 714,
    ""catalogBrandId"": 100,
    ""description"": ""ELEPHANT BIRTHDAY CARD"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/714/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""elephant"",
    ""bgram"": ""birthday"",
    ""abgram"": ""elephant-birthday"",
    ""ygram"": null,
    ""zgram"": ""card"",
    ""yzgram"": ""birthday-card""
  },
  {
    ""id"": 715,
    ""catalogBrandId"": 100,
    ""description"": ""VINTAGE KID DOLLY CARD"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/715/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": ""vintage"",
    ""quantity"": """",
    ""agram"": ""kid"",
    ""bgram"": ""dolly"",
    ""abgram"": ""kid-dolly"",
    ""ygram"": null,
    ""zgram"": ""card"",
    ""yzgram"": ""dolly-card""
  },
  {
    ""id"": 716,
    ""catalogBrandId"": 100,
    ""description"": ""COWBOYS AND INDIANS BIRTHDAY CARD"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/716/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""cowboys"",
    ""bgram"": ""indians"",
    ""abgram"": ""cowboys-indians"",
    ""ygram"": ""birthday"",
    ""zgram"": ""card"",
    ""yzgram"": ""birthday-card""
  },
  {
    ""id"": 717,
    ""catalogBrandId"": 100,
    ""description"": ""BANK ACCOUNT  GREETING  CARD"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/717/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""bank"",
    ""bgram"": ""account"",
    ""abgram"": ""bank-account"",
    ""ygram"": ""greeting"",
    ""zgram"": ""card"",
    ""yzgram"": ""greeting-card""
  },
  {
    ""id"": 718,
    ""catalogBrandId"": 100,
    ""description"": ""GIN & TONIC DIET GREETING CARD"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/718/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""gin"",
    ""bgram"": ""tonic"",
    ""abgram"": ""gin-tonic"",
    ""ygram"": ""greeting"",
    ""zgram"": ""card"",
    ""yzgram"": ""greeting-card""
  },
  {
    ""id"": 719,
    ""catalogBrandId"": 100,
    ""description"": ""BOOZE & WOMEN GREETING CARD"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/719/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""booze"",
    ""bgram"": ""women"",
    ""abgram"": ""booze-women"",
    ""ygram"": ""greeting"",
    ""zgram"": ""card"",
    ""yzgram"": ""greeting-card""
  },
  {
    ""id"": 770,
    ""catalogBrandId"": 100,
    ""description"": ""ELEPHANT CARNIVAL POUFFE"",
    ""price"": 14.95,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/770/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""elephant"",
    ""bgram"": ""carnival"",
    ""abgram"": ""elephant-carnival"",
    ""ygram"": null,
    ""zgram"": ""pouffe"",
    ""yzgram"": ""carnival-pouffe""
  },
  {
    ""id"": 773,
    ""catalogBrandId"": 100,
    ""description"": ""FLOOR CUSHION ELEPHANT CARNIVAL"",
    ""price"": 8.95,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/773/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""floor"",
    ""bgram"": ""cushion"",
    ""abgram"": ""floor-cushion"",
    ""ygram"": ""elephant"",
    ""zgram"": ""carnival"",
    ""yzgram"": ""elephant-carnival""
  },
  {
    ""id"": 887,
    ""catalogBrandId"": 100,
    ""description"": ""VINTAGE SNAP CARDS"",
    ""price"": 0.85,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/887/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": ""vintage"",
    ""quantity"": """",
    ""agram"": ""snap"",
    ""bgram"": null,
    ""abgram"": null,
    ""ygram"": null,
    ""zgram"": ""cards"",
    ""yzgram"": ""snap-cards""
  },
  {
    ""id"": 888,
    ""catalogBrandId"": 100,
    ""description"": ""VINTAGE HEADS AND TAILS CARD GAME"",
    ""price"": 1.25,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/888/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": ""vintage"",
    ""quantity"": """",
    ""agram"": ""heads"",
    ""bgram"": ""tails"",
    ""abgram"": ""heads-tails"",
    ""ygram"": ""card"",
    ""zgram"": ""game"",
    ""yzgram"": ""card-game""
  },
  {
    ""id"": 1026,
    ""catalogBrandId"": 100,
    ""description"": ""EMPIRE BIRTHDAY CARD"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/1026/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""empire"",
    ""bgram"": ""birthday"",
    ""abgram"": ""empire-birthday"",
    ""ygram"": null,
    ""zgram"": ""card"",
    ""yzgram"": ""birthday-card""
  },
  {
    ""id"": 1027,
    ""catalogBrandId"": 100,
    ""description"": ""RAINY LADIES BIRTHDAY CARD"",
    ""price"": 0.42,
    ""pictureUri"": ""http://localhost:5202/api/v1/c/catalog/items/1027/pic/"",
    ""color"": """",
    ""size"": """",
    ""shape"": """",
    ""quantity"": """",
    ""agram"": ""rainy"",
    ""bgram"": ""ladies"",
    ""abgram"": ""rainy-ladies"",
    ""ygram"": ""birthday"",
    ""zgram"": ""card"",
    ""yzgram"": ""birthday-card""
  }
]";
    }
}