//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Bots.Bot.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Bots.Bot.API.Properties.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many *{0}* do you want to buy..
        /// </summary>
        internal static string How_many_do_you_want_to_buy {
            get {
                return ResourceManager.GetString("How_many_do_you_want_to_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did not understand you, please select one brand..
        /// </summary>
        internal static string I_did_not_understand_you__please_select_one_brand {
            get {
                return ResourceManager.GetString("I_did_not_understand_you__please_select_one_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did not understand you, please select one type..
        /// </summary>
        internal static string I_did_not_understand_you_please_select_one_type {
            get {
                return ResourceManager.GetString("I_did_not_understand_you_please_select_one_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your selection or upload a image..
        /// </summary>
        internal static string Please_choose_your_selection_or_upload_a_image_ {
            get {
                return ResourceManager.GetString("Please_choose_your_selection_or_upload_a_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make a selection.
        /// </summary>
        internal static string Please_make_a_selection {
            get {
                return ResourceManager.GetString("Please_make_a_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a brand do you want to search or upload a image to search by image..
        /// </summary>
        internal static string Please_select_a_brand_do_you_want_to_search_or_upload_a_image_to_search_by_image {
            get {
                return ResourceManager.GetString("Please_select_a_brand_do_you_want_to_search_or_upload_a_image_to_search_by_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a item category to seach or upload a image..
        /// </summary>
        internal static string Please_select_a_item_category_to_seach_or_upload_a_image_ {
            get {
                return ResourceManager.GetString("Please_select_a_item_category_to_seach_or_upload_a_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an order..
        /// </summary>
        internal static string Please_select_an_order {
            get {
                return ResourceManager.GetString("Please_select_an_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type a number.
        /// </summary>
        internal static string Please_type_a_number {
            get {
                return ResourceManager.GetString("Please_type_a_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no results matching your search..
        /// </summary>
        internal static string There_are_no_results_matching_your_search {
            get {
                return ResourceManager.GetString("There_are_no_results_matching_your_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type what do you want to do..
        /// </summary>
        internal static string Type_what_do_you_want_to_do {
            get {
                return ResourceManager.GetString("Type_what_do_you_want_to_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can continue shopping..
        /// </summary>
        internal static string You_can_continue_shopping {
            get {
                return ResourceManager.GetString("You_can_continue_shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any orders..
        /// </summary>
        internal static string You_do_not_have_any_orders {
            get {
                return ResourceManager.GetString("You_do_not_have_any_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have added {0} to your basket..
        /// </summary>
        internal static string You_have_added_to_your_basket {
            get {
                return ResourceManager.GetString("You_have_added_to_your_basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged to ckeck your orders..
        /// </summary>
        internal static string You_must_be_logged_to_ckeck_your_orders {
            get {
                return ResourceManager.GetString("You_must_be_logged_to_ckeck_your_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been processed..
        /// </summary>
        internal static string Your_order_has_been_processed {
            get {
                return ResourceManager.GetString("Your_order_has_been_processed", resourceCulture);
            }
        }
    }
}
